runtime: custom
env: flex

env_variables:
  SECRET_KEY: "django-insecure-czzte-066#cktw2)#r1jp&&jwphjge7+6(u$^6zfy1mzc%h7#x"
  DEBUG: "True"

  DB_NAME: "railway"
  DB_USER: "root"
  DB_PASSWORD: "aOhNmnQqXTooXNmxnBbBEKscTNukzSNm"
  DB_HOST: "acela.proxy.rlwy.net"
  DB_PORT: "11578"