services:
  db:
    image: mysql:8.0
    container_name: django_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: student_db
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_sms_app
    command: sh -c "sleep 15 && python manage.py migrate && gunicorn student_system.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: